<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need) Exercises</span></div>

## **Exercise 1** ##

1. Similar:
Both use indexing to locate the position of an element.
Both are used to store data,
3. 2 differences:
You cannot find the number of elements in a 2d list but you can in an array. For a 10x2 table, len(py_list_2d) will give an output of 10 (ie the rows). While len(np_array_2d) gives an output of 10 as well, if you use the attribute 'shape' ie np_array-2d.shape, it will give you the dimensions and consequently the number of elements in the array in the form of (rows,column) ie (10,2). 
In general, python lists approach math by doing the operation to the entire list while arrays approaches each and every element. The format for maths in lists is sum(py_list) while the format for arrays is np.array.sum
4. A dictionary is a storage system that contains a key and value separated by ":". Dictionaries use {} instead of [ ]You can call out the value using dictionary=['key'].

Question 3:
It is not neccessary to use '=' to call out values in a dictionary. The syntax for calling out a value is

dictionary["key"]

e.g

superhero_name["Natasha Romanoff"]

which returns "Black Widow".

## **Exercise 2** ##

In [1]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


## **Exercise 3** ##

In [5]:
elements = ['Hydrogen',
            'Helium', 'Lithium',
            'Beryllium', 'Boron', 'Carbon',
            'Nitrogen', 'Oxygen',
            'Fluorine',
            'Neon'] #neon is index 9 and index -1

print(elements[4])
print(elements[-6])

Boron
Boron


## **Exercise 4** ##

In [3]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]   

import numpy as np
np_array = np.array(numbers) #note: make sure you don't use np.array when redefining your array because it is a function 
                             #the function is no longer callable
                             #use smth else like array or np_array. 
                             #if you made a non-callable function you have to restart the kernel
print(len(np_array)) #or
np_array.shape #format:variable.attribute. you realise that the output will be in the form of (rows,column)

50


(50,)

In [8]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]   

import numpy as np
np_array = np.array(numbers) #note: make sure you don't use np.array when redefining your array because it is a function 
                             #the function is no longer callable
                             #use smth else like array or np_array. 
                             #if you made a non callable function you have to restart the kernal
np_array == 1

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

In [9]:
ones= np_array ==1 #which element in the array = to 1? these elements will be group together into the variable 'ones'
print(sum(ones))

9


In [10]:
ones

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

## **Exercise 5** ##

In [3]:
import numpy as np

In [4]:
x_1 = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
x_2 = [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

array1 = np.array(x_1) #array of x1
array2 = np.array(x_2) #array of x2

### 1. Find the mean of x_1 and x_2 ###

In [5]:
array1.mean() 
print('The mean of x_1 is',array1.mean())
array2.mean() #Finds E(Y)
print('The mean of x_2 is',array2.mean()) 

The mean of x_1 is 38.5
The mean of x_2 is 302.5


### 2. Find the standard deviation of x_1 and x_2 ###


In [6]:
array1.std() #Finds std of x1
print('The standard deviation of x_1 is',array1.std())
array2.std() #Finds std of x2
print('The standard deviation of x_2 is',array2.std())

The standard deviation of x_1 is 32.41990129534635
The standard deviation of x_2 is 326.0893282522444


### 3. Find the standard deviation of x_1 and x_2 ###

The formulas for covariance and correlation were used.
![ ](https://miro.medium.com/v2/resize:fit:1100/format:webp/1*T52-LSuLQyq-6I2c1lkj-A.png)



In [59]:
#Finding covariance

array1.mean() #Finds E(X)
print('The mean of x_1 is',array1.mean())
array2.mean() #Finds E(Y)
print('The mean of x_2 is',array2.mean()) #the comma has to be present

array1_1 = array1 - array1.mean() #Finds x-E(X)
print('array1_1 =', array1_1) 

array2_1 = array2 - array2.mean() #Finds y-E(Y)
print('array2_1 =', array2_1)

product= (array1_1*array2_1) #finds (x-E(X))( y-E(Y))
print('product = ', product)

sum_ofproduct = np.sum(product)
print('sum_ofproduct =',sum_ofproduct)

cov=(1/10)*sum_ofproduct #numpy uses n and not n-1
print('cov =',cov)

The mean of x_1 is 38.5
The mean of x_2 is 302.5
array1_1 = [-37.5 -34.5 -29.5 -22.5 -13.5  -2.5  10.5  25.5  42.5  61.5]
array2_1 = [-301.5 -294.5 -275.5 -238.5 -177.5  -86.5   40.5  209.5  426.5  697.5]
product =  [11306.25 10160.25  8127.25  5366.25  2396.25   216.25   425.25  5342.25
 18126.25 42896.25]
sum_ofproduct = 104362.5
cov = 10436.25


In [60]:
#Finding correlation

array1.std() #Finds std of x1
array2.std() #Finds std of x2

cor=cov/(array1.std()*array2.std())
print('cor =', cor)

cor = 0.9871796626270702


In [48]:
print(np.corrcoef(x_1,x_2)) #the output will find the correlation value of all possible computations
                            # the correlation of x_1 and itself is 1

[[1.         0.98717966]
 [0.98717966 1.        ]]
