#### <div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## **Exercises 1** ##

|Term |Brief Description| 
|:----|:-----|
|Subsetting |Subsetting is a general term used to call out elements in a list/array  |
|Indexing|Indexing calls out a single element|
|Slicing|Slicing calls out a range of elements|
|Masking|Masking calls out a range of elements, while hiding those that aren't called out. This only works in arrays|

## **Exercises 2** ##

In [1]:
# arrays are fussy about type and will convert all things to a single type if they can
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
#the alphabet are strings (denoted by"") while the numbers are something else
np_array_2d[:,0] #this gives an array of the 1st elements in the table

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [2]:
np_array_2d[:,0]
np_array_2d.astype(int) #this will not work because you are finding the integer of the entire array, including the alphabets
#you have to store the data somewhere

ValueError: invalid literal for int() with base 10: np.str_('A')

In [3]:
first_elements= np_array_2d[:,0] #this defines a new array has the first elements
integer_array = first_elements.astype(int)  #makes the first elements into integers, and stores the data in integer_array
print(integer_array)

[ 1  3  2  4  5  7  6  8 10  9]


In [4]:
# Separate the numbers into odd and even using modulo (%). % finds the remainder 
remainder = integer_array% 2
print(remainder)

[1 1 0 0 1 1 0 0 0 1]


In [5]:
#Locate the position(Index) of all of the odd numbers. 
#Note that you cannot mask a
np.where(remainder==1)[0]

array([0, 1, 4, 5, 9])

In [6]:
np_array_2d[:,1]

array(['A', 'C', 'B', 'D', 'E', 'G', 'F', 'H', 'J', 'I'], dtype='<U21')

In [7]:
letters= np_array_2d[:,1]
integer_array[np.where(remainder==1)[0]]
letters[np.where(remainder==1)[0]]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

For this exercise, you want to find the position of all odd numbers and list down the corresponding alphabets.
To do so, you have to find a way to isolate the odd numbers, which we did using modulo (%).
Now that we have identified which positions contain the odd numbers, you need to insert the array that contains the positions into ()() im confused


In [5]:
#corrections

In [9]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
first_elements= np_array_2d[:,0] #defines a new array containing the first elements
integer_array = first_elements.astype(int)  #makes the first elements into integers, and stores the data in integer_array
odd_mask= integer_array% 2==1
odd_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [13]:
np_array_2d[odd_mask] #show only those that are true (ie those that are odd) 

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U21')

In [16]:
odd = np_array_2d[odd_mask] #store the mask
odd_letters= odd[:,1] #show only the letters 
odd_letters

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

## **Exercises 3** ##

In [12]:
import numpy as np

np_array= np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])


np_array[np_array < 50] = -1 #identifies all elements in np_array that are less than 50 and makes the elements into -1
print (np_array) #the format for showing an array that meets the conditions is array[condition]

[[66 50 57 -1 -1]
 [92 -1 88 -1 -1]
 [75 -1 -1 76 -1]
 [-1 51 87 -1 -1]
 [71 -1 67 -1 69]]


In [1]:
import numpy as np

np_array= np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

mask1=np_array < 50
np_array[mask1] = -1 #identifies all elements in np_array that are less than 50 and makes the elements into -1
print(np_array) #note the difference when you print a mask

mask2=np_array>50
np_array[mask2]=1
print(np_array)

mask3=np_array==50 #why is it that = doesn't work but == works
np_array[mask3]= 0
print(np_array)


[[66 50 57 -1 -1]
 [92 -1 88 -1 -1]
 [75 -1 -1 76 -1]
 [-1 51 87 -1 -1]
 [71 -1 67 -1 69]]
[[ 1 50  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
