<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

In [ ]:
#3 ways to store data (list, arrays and dictionary) depends on the users comfort
#Its always python lists and numpy arrays
#Python uses indexes (positions) to locate something in a list ie [a,b,c,d,e] corresponds to [0,1,2,3,4]


In [3]:
import numpy as np
#this is a variable stored in a numpy array
variable = np.array(['index0','index1','index3']) # np.array() and [what's inside the array]

In [1]:
import numpy as np

In [5]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [8]:
np_real_names [1] 

np.str_('Tony Stark')

In [6]:
#reverse indexing counts from the back of the list: negative 1 gives the last element
np_real_names [-1] 

np.str_('Stephen Strange')

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

In [8]:
#dictionary uses keys and values instead of indexing
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

In [9]:
superhero_info['Natasha Romanoff'] #accessing the value using the key (like a lock and key)

'Black Widow'

## 1.4 Higher dimensional lists

In [12]:
#Dictionary uses : to separate the information
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [13]:
#2d list uses brackets in a brackets
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [14]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [20]:
#len() finds the size of the list/array
len(py_list_2d) 
#the output will show that there are 10 rows, but in actual fact there are 20 elements"

10

In [23]:
py_list_2d.shape #there is no such attribute in lists

AttributeError: 'list' object has no attribute 'shape'

In [17]:
len(np_array_2d) 

10

In [19]:
np_array_2d.shape #there are no brackets after shape because shape is an attribute and not a function

(10, 2)

In [18]:
len(np_array_2d) 
np_array_2d.shape

(10, 2)

In [17]:
len(py_list_2d) #len asks for the size of the list but python lists can only determine the 1d size (row)
#2d lists have rows and columns like a table(the list above has 10 rows and 2 columns and therefore 20 "objects"

10

## 2.2 Arrays are fussy about type

In [24]:
#notice how a list allows for integers but numpy is more fussy about types
#all numpy arrays must have the same type

In [26]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)

In [27]:
py_list #calling out the elements in the python list will give you the elements just fine


[1, 1.5, 'A']

In [26]:
np_array #calling out the elements in the array. dtype='<U32' refers to the cata type in the array. this just ensures that each element in the string can be stored such that there is enough space for 32 characters

array(['1', '1.5', 'A'], dtype='<U32')

In [16]:
#just like how you can convert and int to a float, you can convert a list to an array

py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d

[[1, 'A'],
 [2, 'B'],
 [3, 'C'],
 [4, 'D'],
 [5, 'E'],
 [6, 'F'],
 [7, 'G'],
 [8, 'H'],
 [9, 'I'],
 [10, 'J']]

## 2.3 Adding a number

In [28]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [31]:
py_list+10 #doesnt do anything (python is confused) this is different from adding 10 to the list

TypeError: can only concatenate list (not "int") to list

In [29]:
np_array+10 #understands to add 10 to every position

array([11, 12, 13, 14, 15])

## 2.4 Adding another list

## 2.5 Multiplying by a Number

In [34]:
py_list*10 #it just slaps in the list 10 times

[1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5,
 1,
 2,
 3,
 4,
 5]

In [35]:
np_array*10 #actually multiplies the number in each list by 10


array([10, 20, 30, 40, 50])

## 2.6 Squaring

In [37]:
py_list**2 #lists does math to the list as a whole

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [36]:
np_array**2 #array does math to each element (element wise operation)

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [38]:
py_list == 3     #is the list equals to 3?

False

In [40]:
np_array == 3  #are the elements equals to 3? (looks at each element)


array([False, False,  True, False, False])

In [41]:
np_array > 3  #are the elements more than 3 (looks at each element)

array([False, False, False,  True,  True])

In [42]:
# arrays are better at math operations

## 2.8 Mathematics

In [29]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

In [30]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function

1

In [48]:
#notice how jupyter only shows the last result. To display all results you have to print all results

In [47]:
print(sum(py_list))   #hold ctr and click where you want to edit to edit things simultaneously
print(max(py_list))  
print(min(py_list))   

15
5
1


In [32]:
np_array.sum()


np.int64(15)

In [33]:
sum(np.array)

TypeError: 'builtin_function_or_method' object is not iterable

In [54]:
#python cannot find the sum of a 2d list
py_list = [[1,1],[2,1],[3,1],[4,1],[5,1]]


In [55]:
sum(py_list)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [57]:
np_array=np.array(py_list)

In [59]:
#you can specify which rows/columns to add in numpy. 

In [58]:
np_array.sum(axis=1)

array([2, 3, 4, 5, 6])

In [49]:
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

np.float64(1.4142135623730951)

## Footnotes